#setwd("Dropbox/Coursera/Exploratory Data Analysis")
library(lubridate)
library(dplyr)
power<-read.table("household_power_consumption.txt", header=TRUE, sep=";",na.strings="?")
power$Date <- as.Date(power$Date,"%d/%m/%Y")
DateTime <- strptime(power$Time,"%H:%M:%S")
month(DateTime)<-month(power$Date)
year(DateTime)<-year(power$Date)
day(DateTime)<-day(power$Date)
DateTime<-as.POSIXct(DateTime)
power$DateTime<-DateTime
okdates <- as.Date(c("2007-02-01","2007-02-02"))
power2<-filter(power,power$Date %in% okdates)
png(filename="plot2.png",width=480,height=480)
plot(power2$DateTime, power2$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()